# Run once, and it MUST be from an elevated (Administrator) window.
#
# Registers the DWM Growth Sampler scheduled task at RunLevel Highest.
#
# A task registered at Highest runs elevated WITHOUT raising a UAC prompt, so
# this single elevation buys silent capture forever -- including with the screen
# off or over a remote session. Without it, the trap fires but cannot take a
# full dump and cannot run wpr, which is the whole point.
#
# The action is wscript -> a dedicated .vbs (WScript.Shell.Run style 0) ->
# powershell, not powershell directly. Interactive + Highest tasks that launch
# powershell.exe still flash a console even with -WindowStyle Hidden.
# Task Scheduler also mangles multi-arg wscript command lines, so the VBS
# hardcodes the powershell path and script path.
#
# Source is pure ASCII on purpose: PowerShell 5.1 reads BOM-less UTF-8 as ANSI.

param(
  [string]$TaskName        = 'DWM Growth Sampler',
  [int]$IntervalMinutes    = 30,
  # Defaults to the sampler beside this script.
  [string]$Script          = (Join-Path $PSScriptRoot 'dwm-growth-sample.ps1'),
  [string]$LauncherVbs     = (Join-Path $PSScriptRoot 'task-dwm-growth-sample.vbs')
)

$ErrorActionPreference = 'Stop'

$elevated = (New-Object Security.Principal.WindowsPrincipal(
              [Security.Principal.WindowsIdentity]::GetCurrent())
            ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $elevated) {
  Write-Host 'X  Run this from an Administrator window.' -ForegroundColor Red
  exit 1
}
if (-not (Test-Path $Script)) {
  Write-Host "X  Not found: $Script" -ForegroundColor Red
  exit 1
}

$ps  = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
$scriptFull = (Resolve-Path -LiteralPath $Script).Path
$vbsBody = @"
' Auto-generated by dwm-setup-elevated-task.ps1 -- do not edit by hand.
Option Explicit
Dim shell, cmd, rc
Set shell = CreateObject("WScript.Shell")
cmd = """$ps""" & _
      " -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass" & _
      " -File ""$scriptFull"""
rc = shell.Run(cmd, 0, True)
WScript.Quit rc
"@
Set-Content -LiteralPath $LauncherVbs -Value $vbsBody -Encoding ASCII

$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
$arg = "//nologo //B `"$LauncherVbs`""

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

$action = New-ScheduledTaskAction -Execute $wscript -Argument $arg
# No -RepetitionDuration: omitting it means indefinite. Passing
# [TimeSpan]::MaxValue fails with "P99999999DT23H59M59S is out of range".
$t1 = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
        -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)
$t2 = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
# ExecutionTimeLimit was 10 minutes and the capture on 2026-08-11 outgrew it.
# A plain sample takes ~11 s, but when the trap fires the task also runs
# dwm-autocapture.ps1 synchronously: full dump, cdb stacks, then a 30 s WPR trace
# whose MERGE step alone can run for many minutes on a multi-GB ETL. Two earlier
# captures finished in 193 s and 190 s and fit inside 10 minutes. The third
# needed 20 min 40 s, so Task Scheduler terminated the task at the limit
# (LastTaskResult 0x41306, SCHED_S_TASK_TERMINATED).
#
# It survived by accident: killing the task killed the wscript launcher, but the
# powershell and wpr descendants were not in the job object and kept running as
# orphans, finishing the 8.5 GB trace 20 minutes after the task was declared
# dead. Nothing should depend on that. Whether descendants outlive a terminated
# task is not a guarantee, and a capture that only completes because a process
# escaped supervision is a capture that can silently half-complete instead.
#
# 25 minutes, and deliberately not more: with MultipleInstances IgnoreNew and a
# 30-minute interval, this limit is the only thing stopping one wedged run from
# blocking every later sample. At 25 a stuck run costs exactly one skipped
# sample.
$set = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 25) `
        -Hidden
# Highest   = no UAC prompt when the trap fires.
# Interactive = the sampler can see DWM at all; DwmFlush must run inside the
#               interactive session.
$pri = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
        -LogonType Interactive -RunLevel Highest

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $t1,$t2 `
  -Settings $set -Principal $pri | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "Registered.  RunLevel = $($t.Principal.RunLevel)   State = $($t.State)" -ForegroundColor Green
Write-Host "   action : wscript -> $LauncherVbs (no console flash)"
Write-Host "   next run: $((Get-ScheduledTaskInfo -TaskName $TaskName).NextRunTime)"
Write-Host ''
Write-Host 'Optional drill (really does take a full dump plus a 30 s ETL, several GB):'
Write-Host "   powershell -ExecutionPolicy Bypass -File `"$(Join-Path $PSScriptRoot 'dwm-autocapture.ps1')`" -Reason drill"
Write-Host ''
Write-Host 'To undo:'
Write-Host "   Unregister-ScheduledTask -TaskName `"$TaskName`" -Confirm:`$false"
