# Run once. Registers kernel-pool-log.ps1 to take one sample every 30 minutes.
#
# NO ELEVATION. Every counter it reads is available to an ordinary user, so
# there is no UAC prompt and RunLevel stays Limited. This is deliberate: the
# question the sampler answers -- do the pools climb with uptime -- is decidable
# from totals, and per-tag attribution (poolmon, kernel debugger) is a separate
# elevated step to be taken only if the answer is yes.
#
# 30 MINUTES, not 30 seconds. The quantity under test moved 2,834.7 MB over 519
# hours. Sampling faster would add rows without adding information and would put
# the instrument's own cost into the series it is measuring, which this
# investigation has already been caught doing twice.
#
# ONE SAMPLE PER FIRING, not a resident loop. A crash then costs one row rather
# than the rest of the series, and there is no long-lived process to confuse
# with the machine's own behaviour.
#
# AT LOGON AS WELL AS ON INTERVAL. The reading immediately after a boot is the
# most valuable one in the series -- it is the only fresh-kernel baseline -- and
# a pure interval trigger would miss it by up to 30 minutes.
#
# The action is wscript -> a dedicated .vbs (WScript.Shell.Run style 0) ->
# powershell, matching the other watchers here: a task that launches
# powershell.exe directly still flashes a console even with -WindowStyle Hidden.
#
# Source is pure ASCII on purpose: PowerShell 5.1 reads BOM-less UTF-8 as ANSI.

param(
    [string]$TaskName = 'Kernel Pool Sampler',
    [string]$Script = (Join-Path $PSScriptRoot 'kernel-pool-log.ps1'),
    [string]$LauncherVbs = (Join-Path $PSScriptRoot 'task-kernel-pool-log.vbs'),
    [string]$DataDir = $PSScriptRoot,
    [int]$IntervalMinutes = 30
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Script)) {
    Write-Host "X  Not found: $Script" -ForegroundColor Red
    exit 1
}

$ps = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
$scriptFull = (Resolve-Path -LiteralPath $Script).Path
$vbsBody = @"
' Auto-generated by kernel-pool-setup-task.ps1 -- do not edit by hand.
Option Explicit
Dim shell, cmd, rc
Set shell = CreateObject("WScript.Shell")
cmd = """$ps""" & _
      " -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass" & _
      " -File ""$scriptFull""" & _
      " -DataDir ""$DataDir"""
rc = shell.Run(cmd, 0, True)
WScript.Quit rc
"@
Set-Content -LiteralPath $LauncherVbs -Value $vbsBody -Encoding ASCII

$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
$arg = "//nologo //B `"$LauncherVbs`""

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

$action = New-ScheduledTaskAction -Execute $wscript -Argument $arg

# Two triggers: one at logon for the fresh-kernel baseline, one repeating
# indefinitely.
#
# No -RepetitionDuration. Omitting it is what means indefinite, and the two
# obvious ways to say so explicitly both fail: [TimeSpan]::Zero is rejected as
# "(12,26):Duration:PT0S ... incorrectly formatted or out of range", and
# [TimeSpan]::MaxValue as "P99999999DT23H59M59S is out of range". The same
# gotcha is recorded in dwm-setup-elevated-task.ps1; it is repeated here because
# the failure surfaces at Register-ScheduledTask, far from the trigger that
# caused it.
$tLogon = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
$tRepeat = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)

# DontStopIfGoingOnBatteries: uptime accumulates on battery too, and excluding
# unplugged hours would bias the very series being tested against uptime.
# ExecutionTimeLimit 5 minutes is a backstop -- a single sample takes under a
# second, so anything near that is a hang, not slow work.
$set = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5) `
    -Hidden

$pri = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($tLogon, $tRepeat) `
    -Settings $set -Principal $pri | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "Registered.  RunLevel = $($t.Principal.RunLevel)   State = $($t.State)" -ForegroundColor Green
Write-Host "   action   : wscript -> $LauncherVbs (no console flash)"
Write-Host "   interval : every $IntervalMinutes minutes, plus at logon"
Write-Host "   logging  : $DataDir (CSV name is the sampler's own default)"
Write-Host ''
Write-Host 'Take the first sample now without waiting:'
Write-Host "   Start-ScheduledTask -TaskName `"$TaskName`""
Write-Host ''
Write-Host 'Or sample once by hand, printing the row:'
Write-Host "   powershell -NoProfile -File `"$scriptFull`" -Show"
Write-Host ''
Write-Host 'To stop and undo:'
Write-Host "   Stop-ScheduledTask -TaskName `"$TaskName`""
Write-Host "   Unregister-ScheduledTask -TaskName `"$TaskName`" -Confirm:`$false"
