# Run once. Registers load-attrib2-log.ps1 as a resident sampler.
#
# NO ELEVATION. The counters it reads are available to an ordinary user.
#
# The action is wscript -> a dedicated .vbs (WScript.Shell.Run style 0) ->
# pwsh, not pwsh directly. This task used to launch pwsh.exe with
# -WindowStyle Hidden while the task's own Hidden flag was false. On this
# machine Windows Terminal is the default console host, so each start still
# opened an empty PowerShell window. Style 0 does not.
#
# The sampler is a loop, not one sample per firing. ExecutionTimeLimit is
# PT0S. A 10-minute repeat only matters when the previous instance has
# exited; MultipleInstances is IgnoreNew, and the repetition does not stop
# the running instance at the end of the interval.
#
# CSV stays at C:\Users\LZong\Scripts\load-attrib2.csv. That path is the
# script default, so the series already on disk keeps growing.
#
# Source is pure ASCII on purpose: PowerShell 5.1 reads BOM-less UTF-8 as ANSI.

param(
    [string]$TaskName = 'Load Attribution Log v2',
    [string]$Script = (Join-Path $PSScriptRoot 'load-attrib2-log.ps1'),
    [string]$LauncherVbs = (Join-Path $PSScriptRoot 'task-load-attrib2-log.vbs')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Script)) {
    Write-Host "X  Not found: $Script" -ForegroundColor Red
    exit 1
}

$ps = 'C:\Program Files\PowerShell\7\pwsh.exe'
$scriptFull = (Resolve-Path -LiteralPath $Script).Path
$vbsBody = @"
' Auto-generated by load-attrib2-setup-task.ps1 -- do not edit by hand.
Option Explicit
Dim shell, cmd, rc
Set shell = CreateObject("WScript.Shell")
cmd = """$ps""" & _
      " -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass" & _
      " -File ""$scriptFull"""
rc = shell.Run(cmd, 0, True)
WScript.Quit rc
"@
Set-Content -LiteralPath $LauncherVbs -Value $vbsBody -Encoding ASCII

$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
$arg = "//nologo //B `"$LauncherVbs`""

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

$action = New-ScheduledTaskAction -Execute $wscript -Argument $arg
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes 10)

$set = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
    -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1) `
    -Hidden

$pri = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $set -Principal $pri `
    -Description 'Per-process CPU attribution with accounting diagnostics. Read-only. Hidden via wscript.' | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "Registered.  Hidden = $($t.Settings.Hidden)   State = $($t.State)" -ForegroundColor Green
Write-Host "   action  : $($t.Actions[0].Execute) $($t.Actions[0].Arguments)"
Write-Host "   logging : C:\Users\LZong\Scripts\load-attrib2.csv"
