# Run once. Registers ui-response-log.ps1 to start at logon and keep running.
#
# Unlike the DWM sampler this needs NO elevation: GetForegroundWindow and
# SendMessageTimeout work with ordinary user rights, so there is no UAC prompt
# and no RunLevel Highest. It must run Interactive, though -- there is no
# foreground window to probe outside the interactive session.
#
# The task runs indefinitely rather than on an interval, because that is the
# whole point: a stall lasting a few seconds is invisible to a sampler that
# wakes every 30 minutes. ExecutionTimeLimit is therefore disabled (PT0S), and
# restart-on-failure is enabled so a crash does not silently end the logging.
#
# The action is wscript -> a dedicated .vbs (WScript.Shell.Run style 0) ->
# powershell, not powershell directly: Interactive tasks that launch
# powershell.exe still flash a console even with -WindowStyle Hidden. The VBS
# waits on the child so that if the logger dies, the task is seen to fail and
# the restart setting applies.
#
# Source is pure ASCII on purpose: PowerShell 5.1 reads BOM-less UTF-8 as ANSI.

param(
    [string]$TaskName = 'UI Response Logger',
    [string]$Script = (Join-Path $PSScriptRoot 'ui-response-log.ps1'),
    [string]$LauncherVbs = (Join-Path $PSScriptRoot 'task-ui-response-log.vbs'),
    [string]$DataDir = $PSScriptRoot
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Script)) {
    Write-Host "X  Not found: $Script" -ForegroundColor Red
    exit 1
}

$ps = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
$scriptFull = (Resolve-Path -LiteralPath $Script).Path
$vbsBody = @"
' Auto-generated by ui-response-setup-task.ps1 -- do not edit by hand.
Option Explicit
Dim shell, cmd, rc
Set shell = CreateObject("WScript.Shell")
cmd = """$ps""" & _
      " -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass" & _
      " -File ""$scriptFull""" & _
      " -DataDir ""$DataDir"""
rc = shell.Run(cmd, 0, True)
WScript.Quit rc
"@
Set-Content -LiteralPath $LauncherVbs -Value $vbsBody -Encoding ASCII

$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
$arg = "//nologo //B `"$LauncherVbs`""

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

$action = New-ScheduledTaskAction -Execute $wscript -Argument $arg
$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

# ExecutionTimeLimit PT0S = no limit. A task meant to run for days must have
# this disabled explicitly; the default is 3 days, which would silently end
# the logging without any indication in the CSV that it had stopped.
#
# DontStopIfGoingOnBatteries matters here for the same reason it does for the
# DWM sampler: the interesting episodes are not confined to when the machine
# is plugged in.
#
# RestartCount/RestartInterval cover the logger dying unexpectedly. It is
# written to swallow per-probe exceptions, but a process can still be killed
# from outside.
$set = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
    -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
    -Hidden

# Limited, not Highest: this deliberately does not ask for privileges it does
# not need. Interactive is required -- there is no foreground window otherwise.
$pri = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $set -Principal $pri | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "Registered.  RunLevel = $($t.Principal.RunLevel)   State = $($t.State)" -ForegroundColor Green
Write-Host "   action  : wscript -> $LauncherVbs (no console flash)"
Write-Host "   logging : $(Join-Path $DataDir 'ui-response.csv')"
Write-Host "   limit   : $($t.Settings.ExecutionTimeLimit)  (PT0S = runs indefinitely)"
Write-Host ''
Write-Host 'Start it now without waiting for the next logon:'
Write-Host "   Start-ScheduledTask -TaskName `"$TaskName`""
Write-Host ''
Write-Host 'To stop and undo:'
Write-Host "   Stop-ScheduledTask -TaskName `"$TaskName`""
Write-Host "   Unregister-ScheduledTask -TaskName `"$TaskName`" -Confirm:`$false"
